workspace:
  base: /go
  path: src/github.com/uswitch/heimdall

pipeline:
  test:
    image: golang:1.9
    commands:
      - go test -v -cover $(go list ./... | grep -v /vendor)

  build:
    image: golang:1.9
    commands:
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/heimdall

  docker-latest:
    image: plugins/docker
    repo: quay.io/uswitch/heimdall
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
    when:
      event: push
      branch: master

  docker-tagged:
    image: plugins/docker
    repo: quay.io/uswitch/heimdall
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
