// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AlertListerExpansion allows custom methods to be added to
// AlertLister.
type AlertListerExpansion interface{}

// AlertNamespaceListerExpansion allows custom methods to be added to
// AlertNamespaceLister.
type AlertNamespaceListerExpansion interface{}
