// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/uswitch/heimdall/pkg/client/clientset/versioned/typed/heimdall.uswitch.com/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeHeimdallV1alpha1 struct {
	*testing.Fake
}

func (c *FakeHeimdallV1alpha1) Alerts(namespace string) v1alpha1.AlertInterface {
	return &FakeAlerts{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeHeimdallV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
