// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	heimdall_uswitch_com_v1alpha1 "github.com/uswitch/heimdall/pkg/apis/heimdall.uswitch.com/v1alpha1"
	versioned "github.com/uswitch/heimdall/pkg/client/clientset/versioned"
	internalinterfaces "github.com/uswitch/heimdall/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/uswitch/heimdall/pkg/client/listers/heimdall.uswitch.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AlertInformer provides access to a shared informer and lister for
// Alerts.
type AlertInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AlertLister
}

type alertInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAlertInformer constructs a new informer for Alert type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAlertInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAlertInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAlertInformer constructs a new informer for Alert type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAlertInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HeimdallV1alpha1().Alerts(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HeimdallV1alpha1().Alerts(namespace).Watch(options)
			},
		},
		&heimdall_uswitch_com_v1alpha1.Alert{},
		resyncPeriod,
		indexers,
	)
}

func (f *alertInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAlertInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *alertInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&heimdall_uswitch_com_v1alpha1.Alert{}, f.defaultInformer)
}

func (f *alertInformer) Lister() v1alpha1.AlertLister {
	return v1alpha1.NewAlertLister(f.Informer().GetIndexer())
}
